### ISSUE TITLE
Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by MJEddie** [MJEddie/La-Vie-Verte#1]
## 問題
要運行 vue 環境時報錯
![image](https://user-images.githubusercontent.com/50713298/138997405-8ca30b47-df5f-44d4-b421-d0fbd1bfffc8.png)

嘗試安裝 `node-sass `後的訊息畫面
![image](https://user-images.githubusercontent.com/50713298/138998713-c7f54653-79e1-44a3-aaf0-0b4eb1b953fa.png)

無法安裝 `node-sass`，無法運行 vue 環境

## 使用環境
windows
Node.js 版本
```
v11.7.0
```
npm 版本
```
6.5.0
```

@LukaHuang 求救

**Comment by LukaHuang** [comment]
看起來好像是node.js sass版本不批
匹配
npm uninstall node-sass
npm install node-sass

MJEddie ***@***.***> 於 2021年10月27日 週三 12:22 寫道：

**Comment by MJEddie** [comment]
重新安裝 node-sass 後運行報以下錯誤

![image](https://user-images.githubusercontent.com/50713298/139034053-bffed4c8-ec91-4d00-84bc-5926f04753bb.png)

嘗試了幾種方法：

1. 移除舊版本的 node-sass，接著安裝 4.0.0 版本，依舊不行
```
npm uninstall node-sass
npm install node-sass@4.14.1
```
2. 安裝不同版本，依舊不行
```diff
- "node-sass": "^4.0",
+ "node-sass": "^6.0",
- "sass-loader": "^7.1.0",
+ "sass-loader": "^12.0",
```
最後解決方式

```
npm uninstall node-sass
npm install sass
```

**Comment by LukaHuang** [comment]
嗯嗯 環境問題就是google一下看看當前版本有沒有問題
